### ISSUE TITLE
Psuedoizer should not Pseudo HTTP or HTTPS links

### ISSUE THREAD

**Issue by tiernano** [shanselman/Psuedoizer#8]
If you pass a HTTP or HTTPS link into ConvertToFakeInternationalized function, it will localize it... Maybe it shouldent...

**Comment by rgamage** [comment]
I imagine this may have come up before, but, maybe the repo name should be "Ps**eu**doizer" rather than "Ps**ue**doizer"?

**Comment by shanselman** [comment]
@rgamage Thanks for this! I am SCANDALIZED that I've never noticed it and TWICE so that you're the first person in nearly a decade to notice.

LOL I'm not sure what we should do. I'd need to fix hundreds of links. Lemme see if it'll redirect
